# **GR5242 HW03 Problem 1: Automatic Differentiation**

**Instructions**: This problem is an individual assignment -- you are to complete this problem on your own, without conferring with your classmates.  You should submit a completed and published notebook to Courseworks; no other files will be accepted.

## Description:

This homework adds more detail to the autodiff lecture in class. There are seven questions (30 points) in total, which include coding and written questions. You can only modify the codes and text within \### YOUR CODE HERE ### and/or \### YOUR ANSWER HERE ###.


In [1]:
import torch
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime
import sympy as sym

## Differentiation

**Different ways of differentiation:** In this problem we consider a particular function (which we call it an `op` in the code block, short for operation) $f:\mathbb{R} \to \mathbb{R}: x \mapsto 4x(1-x)$ and it's compositions with itself. Let us define,
$$ g_n: \underbrace{f \circ \dots \circ f}_{n \text{ times}}: x \mapsto f^{(n)}(x) $$
where $f^{(n)}(x) = f(f^{(n-1)}(x))$ is the $n$ times composited function $f$ with itself. The goal of this problem is to explore various ways of differentiation, i.e. $\frac{d}{dx}g_{n}(x)$ which are listed below:
- Numerical differentiation
- Symbolic differentiation
- Autodiff in forward or reverse mode

In [2]:
def op(inp):
    return 4 * inp * ( 1 - inp )

def operation(inp, n = 1):
    temp = inp
    for i in range(n):
        temp = op(temp)
    return temp
    

## Numerical Differentiation

Based on the definition of derivative at a particular point $x_0$,

$$ \frac{d}{dx}g_n(x_0) = \lim_{h \to 0} \frac{g_n(x_0+h) - g_n(x_0)}{h} =: \lim_{h \to 0} D_h g_n(x_0) $$

The formula above suggests a simple way of **approximating** the derivative by taking $D_{h}g_n(x_0)$ for a particular choice of $h$ as your approximate derivative. This is also known as the [finite difference](https://en.wikipedia.org/wiki/Numerical_differentiation) method. Note that this approach only requires evaluation of your function around the point you are trying to take the derivative at so it's computationally efficient but the caveat is that choosing a proper $h$ to obtain good enough approximations is generally hard (specially when the function is multivariate). However, in our case we have some structure over the function we are trying to take derivative of.

**Question 1 (3 points)**: Use a finite difference with tolerance 1e-12 to approximate the derivative of $g_3(x)$ at $x=1$:

In [3]:
tol = 1e-12
### Your Code Here ###
(operation(inp=1+tol, n=3)-operation(inp=1, n=3))/ tol

-64.00568963861407

The approximation will be bad at certain points $x$, and becomes less stable as $n$ becomes larger for a fixed $h$ (or as the dimensionality of the function grows).  

## Calculus and (manual/symbolic) differentiation

Notice that $f$ is a polynomial and that composition of polynomials yields also a polynomial. Therefore, $g_n$ is a polynomial with degree $2^n$ (try to argue this for yourself using induction); we can compute the derivative using  calculus.

Instead of computing the derivative by hand we use the help of an auxillary package `sympy` and try to compute the derivative. This package uses symbolic variables and traces operations such as add, multiplication, division, etc., applied onto these variables and computes the derivative using chain rule.

It is not difficult to (manually) derive a closed form expression for $g_n$ using the recursive formula
$$ g_n(x) = 4 g_{n-1}(x) (1-g_{n-1}(x)), \quad g_{1}(x) = 4x(1-x).$$  
The following block of code prints this closed form expression in terms of a symbolic variable `X`.

In [4]:
X = sym.Symbol('X') # Create a symbolic variable
sym.init_printing(use_unicode=False, wrap_line=True)

Now that we have the closed form expression, we may use the chain rule to express the derivative of $g_n$.

In [5]:
Y = operation(X, 3)
dydx_symbolic = sym.diff(Y, X)
dydx_symbolic

C:\Users\zha\.conda\envs\tf2\lib\site-packages\IPython\lib\latextools.py:126: MatplotlibDeprecationWarning: 
The to_png function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
C:\Users\zha\.conda\envs\tf2\lib\site-packages\IPython\lib\latextools.py:126: MatplotlibDeprecationWarning: 
The to_rgba function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
C:\Users\zha\.conda\envs\tf2\lib\site-packages\IPython\lib\latextools.py:126: MatplotlibDeprecationWarning: 
The to_mask function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
C:\Users\zha\.conda\envs\tf2\lib\site-packages\IPython\lib\latextools.py:126: MatplotlibDeprecationWarning:

**Question 2 (3 points):** Compute the exact derivative of $g_n(x)$ at $x=1$ by evaluating the symbolic expression.

In [6]:
# hint: read about subs/evalf here: https://docs.sympy.org/latest/modules/numeric-computation.html
### Your Code Here ###
from sympy import *
from sympy.abc import x
dydx_symbolic.evalf(subs={X: 1})

As it is evident the closed form expression for `dydx_symbolic` is unwieldy. We can make it more efficient by expanding and collecting all the terms. The goal is to represent the derivative as a natural polynomial. Yet this is another way of computing the derivative.

**Question 3 (3 points):** Using the `sympy` documentation [page](https://docs.sympy.org/latest/tutorials/intro-tutorial/simplification.html) expand/simplify the closed form expression of $g_n(x)$ and print its derivative as a symbolic expression.

In [7]:
### Your Code Here ###
polynomial = dydx_symbolic
dydx_symbolic_simplified = expand(polynomial)
dydx_symbolic_simplified # This should express a polynomial of degree 2^n - 1.

Now that we have a compact closed form for the derivative we can evaluate it efficiently at various values of $x$.

**Question 4 (2 points):** Evaluate `dydx_symbolic_simplified` at $x=1$.

In [8]:
### Your Code Here ###
dydx_symbolic_simplified.evalf(subs={X: 1}), -131072+458752-638976+450560-168960+32256-2688+64

## Chain Rule and Autodiff

As we've seen in the previous part, symbolic engines computes the derivative using **some** closed form expression of the function. In particular, `sympy` simplified the **recursive** operation and expressed the function $g_n$ in terms of basic operations over the symbolic variable `X`. On the other hand, Autodiff does not necessarily simplify these operations and apply chain rule directly to the latest operation either in forward or backward mode.


**Question 5 (4 points):** Using the recursive representation $g_n(x) = f(g_{n-1}(x))$ calculate the derivative of $g_n$ as a function of $g_{n-1}$ and $g^{'}_{n-1}$.  (To be clear, this part is not code; write the mathematical expression below)

 '### Your Answer Here ###'

**Answer:** Using chain rule we have,
$$g_n^{'}(x) = 4 g_{n-1}^{'}(x)(1-g_{n-1}(x)) - 4 g_{n-1}^{'}(x) g_{n-1}(x) = 4 g_{n-1}^{'}(x) - 8g_{n-1}^{'}(x) g_{n-1}(x) $$

This implies that we can compute $g_{n}^{'}(x)$ in the forward mode if we could compute $g_{n-1}(x)$ and $g_{n-1}^{'}(x)$ in the forward mode. Indeed, this is possible by applying the same logic to $g_{n-1}^{'}(x)$ and compute it based on $g_{n-2}(x)$ and $g_{n-2}^{'}(x)$; In other words, by augmenting the forward computation graph $g_1 \to g_2 \dots \to g_n$ with $(g_1, g_1^{'})\to (g_2,g_2^{'}),\dots \to (g_n,g_n^{'})$ we can compute the derivative in a forward pass.

**Question 6 (8 points):** Modify the functions `op` and `operation` with their counterparts `op_with_grad` and `operation_with_grad` using the logic explained above to compute the derivative of $g_n$. Check your function by evaluating it at $x=1$.

In [9]:
### Your Code Here ###
def op_with_grad(inp, grad):
  # inp could be any function of x.
  # grad is the corresponsing derivative of inp with respect to x.
  # The function should return a tuple where the first element is the `op` applied to inp
  # and the second element should be the gradient of op(inp) with respect to x.
    return(op(inp), 4*grad-8*grad*inp)
    pass

    

def operation_with_grad(inp, n = 1):
  # inp represents x here.
  # This function should output a tuple where the first element is the value of g_n(inp)
  # and the second element should be the derivative evaluated at inp, i.e. g_n^'(inp)
    temp = inp
    grad = 1
    for i in range(n):
        temp, grad = op_with_grad(temp, grad) # apply this operation n times
    return (temp, grad)
    pass

operation_with_grad(1.0, n = 3)

Fortunately, `torch` can do last part for us! As was discussed in class, `torch` interprets our code and builds up a computation graph using operations that knows their gradients already and complements each operation with their backward gradient; in order to compute the gradient it follows the following backwards path

$$ (g_n, \frac{\partial}{\partial g_n}g_n) \to (g_{n-1}, \frac{\partial}{\partial g_{n-1}}g_{n}) \to (g_1, \frac{\partial}{\partial g_1}g_n) \to (g_0, \frac{\partial}{\partial g_0}g_n) $$

where $g_0(x) = x$ is the identity function.

**Question 7 (7 points):** Use PyTorch to calculate the derivative of g_n(x) with respect to x

In [53]:
def torch_op(inp):
    return 4 * inp * ( 1 - inp )

def torch_operation(inp, n = 1):
    temp = inp
    for i in range(n):
        temp = torch_op(temp)
        temp.retain_grad()# apply this operation n times
    return temp

In [60]:
x = torch.tensor(1.0, requires_grad=True)

#### Your code here #####
# define the function with n=3 iterations as before, and use pytorch to autodiff it!
y = torch_op(x)
y.retain_grad()
z = torch_op(y)
z.retain_grad()
gn = torch_op(z)
# gn = torch_operation(x, n = 3)
gn.backward()
df_dx = x.grad
print(df_dx.numpy())
y.grad, z.grad

-64.0


(tensor(16.), tensor(4.))

In [52]:
xx = torch.randn(1,1, requires_grad = True)
yy = 3*xx
yy.retain_grad()
zz = yy**2
zz.backward()

xx.grad 
yy.grad

tensor([[5.8529]])

In [3]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
Q = 3*a**3 - b**2
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

In [1]:
import torch
# create a 2x3 input tensor
input_tensor = torch.tensor([[1.0, 2.0, 3.0],
                             [4.0, 5.0, 6.0]])
# apply log_softmax along dimension 1
output_tensor = torch.nn.functional.log_softmax(input_tensor, dim=1)
print(output_tensor)

tensor([[-2.4076, -1.4076, -0.4076],
        [-2.4076, -1.4076, -0.4076]])


In [2]:
torch.empty(3, dtype=torch.long).random_(5)

tensor([3, 4, 0])